<article class="main-text two-third column clima">
    <h2>Clima</h2>
    <p>
        O tipo climático da região é o Equatorial com calor intenso e úmido,
        com temperaturas médias acima de 28°C.
    </p>
    <img src="../assets/images/mapa_estado_clima_g.gif" alt="" />
    <h2>Bioma: Floresta</h2>
    <p>
        A Amazônia representa mais da metade das florestas tropicais no
        planeta e tem a maior biodiversidade em uma floresta tropical no
        mundo.
    </p>
    <img src="../assets/images/amazonia-bioma.jpg" alt="" />
</article>