<article class="main-text two-third column">
    <h2>Desmatamento</h2>
    <p>A ocupação humana se intensificou durante o chamado “ciclo da borracha”, e assim como a extração das chamadas “drogas do sertão”, para a produção de medicamentos, não ameaçou o equilíbrio já que não precisava retirar as árvores. </p>
    <p>Já o garimpo, resultou em consequências graves do ponto de vista ambiental, devido à contaminação por mercúrio dos rios amazônicos. </p>
    <p><img class="img-right" src="./assets/images/madeireira-768x576.jpeg" alt="" width="300px">
        A isso se somou o avanço da pecuária, trazendo as grandes queimadas para eliminar a vegetação arbórea e abrir espaço às pastagens, além das atividades das madeireiras, que exploram as madeiras nobres requeridas pelos mercados consumidores dos países ricos.</p>
    <p>A ocupação do território adquiriu novas características que claramente entram em conflito com a preservação do meio ambiente.</p>
    <p><img class="img-left" src="./assets/images/incendio-amazonia-Foto-Fernando-Frazão-ABr.jpg" alt="" width="300px">
        Essa ocupação desorganizada é a causa das queimadas feitas pelos agricultores, que saíram do controle humano e, com a ajuda da seca que afeta a região, provoca também os mais graves incêndios já registrados em terras amazônicas.</p>
</article>