<article class="main-text two-third column">
    <h2>Fauna</h2>
    <p>
        A fauna Amazônica é considerada uma das maiores reservas viva do
        planeta. Existem cerca de 6 milhões espécies de animais mamíferos,
        aves, peixes, insetos, vermes, rotíferos, protozoários, bactérias e
        fungos, fazendo parte de uma complexa e rica teia alimentar. A maior parte da fauna amazônica é de animais que habitam as
        copas das árvores, entre 30 e 50 metros, já que a vegetação rasteira
        é muito escassa, devido a dificuldade da entrada de luz por causa
        das copas abundantes das árvores. A dificuldade de acesso às altas
        copas, faz com que grande parte da fauna ainda seja desconhecida.
        Mesmo assim sabe-se da existência de mais de 1300 espécies de
        pássaros e mais de 300 mamíferos diferentes.
        Dentre os animais encontrados na Floresta Amazônica, podemos destacar: jacarés, serpentes, como a sucuri, várias espécies de sapos, rãs e pererecas, e uma grande variedade de aves, como tucanos, araras e o galo-da-serra. Insetos, como formigas, mariposas, borboletas e besouros, são também abundantes.

    </p>
    <div class="gallery">
        <img src="../assets/images/boto-rosa.jpg" alt="" />
        <img src="../assets/images/Casal-de-Arara-de-Barriga-Amarela-Amazonia-Blog-Escola-e-educação.jpg" alt="" />
        <img src="../assets/images/onça-pintada.jpg" alt="" />
        <img src="../assets/images/RTEmagicC_Uacari-branco-instituto-mamiraua__1_.jpg.jpg" alt="" />
    </div>
    <h2>Flora</h2>
    <p>
        A flora contém mais de 60 mil espécies diferentes de árvores,
        algumas gigantescas com mais de 100 m de altura. Uma grande
        diversidade de árvores frutíferas que fornece sabores únicos e
        encantam o paladar de qualquer pessoa fornecendo energia e vitaminas
        a quem as consome. O Cupuaçu, o Açaí - poderoso energético que já é
        consumido em outros países, a Pupunha - uva da Amazônia, com seus
        deliciosos frutos em cachos, que só podem ser consumidos após o
        cozimento, entre outros. Contém a maior fonte natural no mundo para
        produtos farmacêuticos e bioquímicos.
    </p>
    <div class="gallery">
        <img src="../assets/images/800px-Victoria_amazonica,_2015-08-08,_Phipps_Conservatory,_08.jpg" alt="" />
        <img src="../assets/images/samauma.jpg" alt="" />
    </div>
    <h2>Outros recursos naturais</h2>
    <p>
        A Amazônia ainda possui jazidas minerais de metais nobres dos mais
        variados tipos, acumulando recursos da ordem de trilhões de dólares.
    </p>
</article>