<article class="main-text two-third column">
    <div class="gallery">
        <div class="card">
            <a href="./assets/images/800px-Victoria_amazonica,_2015-08-08,_Phipps_Conservatory,_08.jpg" target="_blank"><img src="./assets/images/800px-Victoria_amazonica,_2015-08-08,_Phipps_Conservatory,_08.jpg" alt="" onclick="document.baseURI" />
            </a>
            <p>Vitória-régia</p>
        </div>

        <div class="card">
            <a href="./assets/images/amazonas-600x400.jpg" target="_blank"><img src="./assets/images/amazonas-600x400.jpg" alt="" onclick="document.baseURI" />
            </a>
            <p>Vitória-régia</p>
        </div>

        <div class="card">
            <a href="./assets/images/açai.jpg" target="_blank"><img src="./assets/images/açai.jpg" alt="" onclick="document.baseURI" />
            </a>
            <p>Açaí</p>
        </div>

        <div class="card">
            <a href="./assets/images/samauma.jpg" target="_blank"><img src="./assets/images/samauma.jpg" alt="" onclick="document.baseURI" />
            </a>
            <p>Samauma</p>
        </div>

        <div class="card">
            <a href="./assets/images/10-nao-ha-pontes-sobre-o-rio-amazonas-1484665286640_615x300.jpg" target="_blank"><img src="./assets/images/10-nao-ha-pontes-sobre-o-rio-amazonas-1484665286640_615x300.jpg" alt="" onclick="document.baseURI" />
            </a>
            <p>Floresta Amazônica</p>
        </div>

        <div class="card">
            <a href="./assets/images/whatsapp-image-2019-09-02-at-14.52.51.jpeg" target="_blank"><img src="./assets/images/whatsapp-image-2019-09-02-at-14.52.51.jpeg" alt="" onclick="document.baseURI" />
            </a>
            <p>Angelim vermelho</p>
        </div>

        <div class="card">
            <a href="./assets/images/peixe-boi-amazonia.jpg" target="_blank"><img src="./assets/images/peixe-boi-amazonia.jpg" alt="" onclick="document.baseURI" />
            </a>
            <p>Peixe boi</p>
        </div>

        <div class="card">
            <a href="./assets/images/Casal-de-Arara-de-Barriga-Amarela-Amazonia-Blog-Escola-e-educação.jpg" target="_blank"><img src="./assets/images/Casal-de-Arara-de-Barriga-Amarela-Amazonia-Blog-Escola-e-educação.jpg" alt="" onclick="document.baseURI" />
            </a>
            <p>Arara de barriga amarela</p>
        </div>

        <div class="card">
            <a href="./assets/images/onça-pintada.jpg" target="_blank"><img src="./assets/images/onça-pintada.jpg" alt="" onclick="document.baseURI" />
            </a>
            <p>Onça pintada</p>
        </div>

        <div class="card">
            <a href="./assets/images/RTEmagicC_Uacari-branco-instituto-mamiraua__1_.jpg.jpg" target="_blank"><img src="./assets/images/RTEmagicC_Uacari-branco-instituto-mamiraua__1_.jpg.jpg" alt="" onclick="document.baseURI" />
            </a>
            <p>Uacari branco</p>
        </div>

        <div class="card">
            <a href="./assets/images/boto-rosa.jpg" target="_blank"><img src="./assets/images/boto-rosa.jpg" alt="" onclick="document.baseURI" />
            </a>
            <p>Boto rosa</p>
        </div>

        <div class="card">
            <a href="./assets/images/3727211981_c3ce2367f7_o-600x398.jpg" target="_blank"><img src="./assets/images/3727211981_c3ce2367f7_o-600x398.jpg" alt="" onclick="document.baseURI" />
            </a>
            <p>Mico-leão-dourado</p>
        </div>
    </div>
</article>