<article class="main-text two-third column">
    <h2>Introdução</h2>
    <p>
        A Amazônia, é uma floresta de clima tropical, ou seja, possui a maior biodiversidade de espécies de fauna e flora.
        Está predominantemente localizada na Região Norte do Brasil, e também se encontra em outros países da América do Sul, como a Bolívia, Colômbia, Equador, Guiana, Guiana Francesa, Peru, Suriname e Venezuela.

    </p>
    <img src="../assets/images/CBERS-04A..jpg" alt="" width="100%" />
</article>