<article class="main-text two-third column">
    <h2>Extensão Territorial</h2>
    <p>
        A Amazônia tem uma extensão territorial de 6.700.000 km² sendo o
        maior bioma brasileiro, tendo uma grande fauna e flora tornando-a muito conhecida.
    </p>
    <h2>Paisagem</h2>
    <p>A paisagem da Amazônia é formada por muitas arvores, rios e lagos e uma boa parte plana.</p>
    <h2>O Rio</h2>
    <p>
        A região que recebe o nome de Amazônia (no Brasil) corresponde a
        bacia hidrográfica da Amazônia, composta de inúmeros rios e
        igarapés. Seu principal rio é o Amazonas, cuja largura varia entre
        quatro e cinco quilômetros, chegando a medir em alguns trechos até
        dez quilômetros de extensão. Com uma área de cerca de 5 mil Km²,
        equivalente a 59% do Brasil, a bacia da Amazônia é a maior do mundo.
        O rio Amazonas nasce no Peru e recebe vários nomes, até entrar no
        Brasil como Solimões. A partir de Manaus recebe o nome de Amazonas
        até a sua foz no oceano Atlântico. Seus principais afluentes são:
        Madeira, Japurá, Negro (que é o mais extenso rio de água negra do
        mundo), Trombetas, Tapajós, etc... Nas águas desses rios existem
        mais de 1.400 tipos de peixes.
    </p>
    <img src="./assets/images/10-nao-ha-pontes-sobre-o-rio-amazonas-1484665286640_615x300.jpg" alt="" width="100%" />
</article>