<article class="main-text two-third column vegetacao">
    <h2>Vegetação</h2>
    <h3>Várzea</h3>
    <p>Floresta de várzea é um tipo de floresta de planícies inundáveis invadidas por enchentes sazonais na bacia Amazônica, ao longo de rios de "águas brancas". Ao longo do rio Amazonas e muitos de seus tributários, há uma alta taxa pluviométrica durante a estação das chuvas, resultando em grandes enchentes estacionais.</p>
    <img src="../assets/images/varzea.jpg" alt="">
    <h3>Matas de Igapó</h3>
    <p>As matas de igapó situam-se nos terrenos mais baixos e permanecem quase sempre inundadas. Nelas a vegetação é baixa, com arbustos, cipós e musgos. Também são encontradas plantas aquáticas, como a vitória-régia, um dos símbolos da Amazônia.</p>
    <img src="../assets/images/igapo.jpg" alt="">
    <h3>Caatingas Amazônicas</h3>
    <p>Caatinga é um bioma brasileiro que apresenta clima semiárido, vegetação com pouca folhas e adaptadas para os períodos de secas, além de grande biodiversidade. O clima da Amazônia é equatorial, caracterizado por elevadas temperaturas e grande índice pluviométrico.</p>
    <img src="../assets/images/caatinga.jpg" alt="">
    <h3>Vegetação litorânea (mangue)</h3>
    <p>A Vegetação Litorânea (mangues) são ecossistemas costeiros presentes em regiões tropicais e subtropicais em que há o encontro de águas dos rios e dos mares.</p>
    <img src="../assets/images/mangue.jpg" alt="">
    <h3>Vegetação serrana</h3>
    <p>O tipo dominante nessas serras é a floresta densa, chamada floresta serrana ou brejo de altitude, associada à floresta aberta nas escarpas médias e inferiores voltadas para a direção dos ventos, há vegetação caducifólia espinhosa.</p>
    <img src="../assets/images/serrana.jpg" alt="">
</article>