</section>
<footer id="main-footer">
    <div class="row">
        <div class="one column">
            <h4>Saiba mais:</h4>
            <nav class="footer-menu">
                <a href="http://www.obosque.com.br/" target="_blank"><img src="./images/logo.png" alt="" width="50px" /></a>
                <a href="https://www.icmbio.gov.br/portal/" target="_blank"><img src="./images/logo_icmbio.png" alt="" width="50px" /></a>
                <a href="https://imazon.org.br/" target="_blank"><img src="./images/logo-imazon_transp.png" alt="" width="80px" /></a>
                <a href="http://www.fundoamazonia.gov.br/pt/home/" target="_blank"><img src="./images/ID_FundaAmazonia_PT.png" alt="" width="80px" /></a>
            </nav>
            <p>&copy; Antonio Carlos Zaninete Fiad - 2020</p>
        </div>
    </div>
</footer>
</body>

</html>