<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8" />
    <meta name="keywords" content="Amazonia, pesquisa escolar, Colegio O Bosque" />
    <meta name="description" content="Mostra cultural 2020 - Colegio O Bosque - Tema Amazonia" />
    <meta name="author" content="Antonio Carlos Zaninete Fiad" />
    <meta name="robots" content="index, follow" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>* Colégio O Bosque *</title>
    <link rel="stylesheet" href="./assets/css/normalize.css" />
    <link rel="stylesheet" href="./assets/css/fonts.css" />
    <link rel="stylesheet" href="./assets/css/grid.css?v1.0" />
    <link rel="stylesheet" href="./assets/css/app.css?v1.0" />
</head>

<body>
    <header id="header">
        <div class="row">
            <div class="one column">
                <div class="title">
                    <h2>Trabalho de Ciências: <i>Prof. Leandro<i></h2>
                    <h1>"FLORESTA AMAZÔNICA E SUAS CARACTERÍSTICAS"</h1>
                    <h2>Grupo - 7º A</h2>
                </div>
            </div>
        </div>
    </header>

    <section id="main-area" class="row">
        <div class="container main-back">
            <nav class="main-menu one-fourth column">
                <a href="./" class="main-nav">Introdução</a>
                <a href="./paisagem" class="main-nav">Paisagem</a>
                <a href="./clima" class="main-nav">Clima e bioma</a>
                <a href="./fauna" class="main-nav">Fauna e flora</a>
                <a href="./vegetacao" class="main-nav">Tipos de Vegetação</a>
                <a href="./desmatamento" class="main-nav">Desmatamento</a>
                <a href="./video" class="main-nav">Assista o vídeo</a>
                <a href="./galeria" class="main-nav">Galeria</a>
            </nav>